//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEventStore.Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NEventStore.Api.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day should be between 1 and {0}.
        /// </summary>
        internal static string DayOutOfRange {
            get {
                return ResourceManager.GetString("DayOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From should be 0 or more.
        /// </summary>
        internal static string FromOutOfRange {
            get {
                return ResourceManager.GetString("FromOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unspecidied error occurred while processing your request.
        /// </summary>
        internal static string GeneralExceptionMessage {
            get {
                return ResourceManager.GetString("GeneralExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Event Library Plugin {0}.
        /// </summary>
        internal static string LoadingEventLibraryPlugin {
            get {
                return ResourceManager.GetString("LoadingEventLibraryPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month shoud be between 1 and 12.
        /// </summary>
        internal static string MonthOutOfRange {
            get {
                return ResourceManager.GetString("MonthOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream id should not be null.
        /// </summary>
        internal static string NullStreamId {
            get {
                return ResourceManager.GetString("NullStreamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number should be 0 or more.
        /// </summary>
        internal static string NumberOutOfRange {
            get {
                return ResourceManager.GetString("NumberOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take should be 1 or more.
        /// </summary>
        internal static string TakeOutOfRange {
            get {
                return ResourceManager.GetString("TakeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown stream type.
        /// </summary>
        internal static string UnknownStreamType {
            get {
                return ResourceManager.GetString("UnknownStreamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year should be greater than 1900.
        /// </summary>
        internal static string YearOutOfRange {
            get {
                return ResourceManager.GetString("YearOutOfRange", resourceCulture);
            }
        }
    }
}
